config/routes.rb
Rails.application.routes.draw do
  resources :people
  root "people#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
    
  scope :get_ordered, -> { order("created_at DESC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :find_person, only: [:edit, :update, :destroy]
  
  def index
    @people = Person.get_ordered
  end
  
  def new
    @person = Person.new
    respond_to do |format|
      format.js  # new.js.erb
    end
  end
  
  def create
    @person = Person.new(person_params)
    if @person.save
      @people = Person.get_ordered
      respond_to do |format|
        format.js # create.js.erb  
      end
    end
  end
  
  def edit
    respond_to do |format|
      format.js # edit.js.erb
    end
  end
  
  def update
    if @person.update(person_params)
      @people = Person.get_ordered
      respond_to do |format|
        format.js # update.js.erb  
      end
    end
  end
  
  def destroy
    if @person.destroy
      @people = Person.get_ordered
      respond_to do |format|
        format.js # destroy.js.erb  
      end
    end
  end
  
  private
  
  def find_person
    @person = Person.find(params[:id])
  end
  
  def person_params
    params.require(:person).permit(:first_name, :last_name, :country)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnePageCrud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">One Page CRUD</a>
        </div>
    
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
          </ul>  
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= simple_form_for @person, remote: true do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :country, prompt: "Select Country" %>
  
  <% if @person.persisted? %>
    <%= f.submit "Update", class: "btn btn-success",
        data: { disable_with: "Updating..." } %>
  <% else %>
    <%= f.submit " Add ", class: "btn btn-success",
        data: { disable_with: "Adding..." } %>
  <% end %>
<% end %>

app/views/people/_person.html.erb
<li class="list-group-item person-item">
  <%= "#{person.first_name} #{person.last_name} - #{person.country}" %>
  <span class="person-buttons">
    <%= link_to "Edit", edit_person_path(person), remote: true,
        class: "btn btn-primary", data: { disable_with: "Edit..." } %>
    <%= link_to "Delete", person_path(person), method: :delete, remote: true,
        class: "btn btn-danger", data: { disable_with: "Delete...",
        confirm: "Are you sure you want to delete this record?" } %>    
  </span>
</li>

app/views/people/create.js.erb
$("#people-list").html("<%= j(render @people) %>");
$("#person-form").slideUp();

app/views/people/destroy.js.erb
$("#people-list").html("<%= j(render @people) %>");

app/views/people/edit.js.erb
$("#person-form").html("<%= j(render 'form') %>");
$("#person-form").slideDown();

app/views/people/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <%= link_to "Add Person", new_person_path, remote: true,
        class: "btn btn-primary", data: { disable_with: "Add Person..." } %>
       
      <div id="person-form">
            
      </div>
      
      <ul id="people-list" class="list-group">
        <%= render @people %>
      </ul>
      
    </div>      
  </div>
</div>

app/views/people/new.js.erb
$("#person-form").html("<%= j(render 'form') %>");
$("#person-form").slideDown();

app/views/people/update.js.erb
$("#people-list").html("<%= j(render @people) %>");
$("#person-form").slideUp();